server:
  port: 8899

spring:
  application:
    name: kotlin-spring-data-mongo-reactive
  profiles:
    active: local

autoconfigure:
  exclude:
    - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

management:
  server:
    port: 9191
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

mongodb:
  uri: mongodb://localhost:27017
  info:
    test:
      database: test

logging:
  pattern:
  #console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    pe.kotlin.mongo: debug
    org.springframework: debug
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug

